[project]
name = "chatbot-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.0.5",
    "langchain-openai>=1.0.2",
    "loguru>=0.7.3",
    "streamlit>=1.51.0",
]
